### ISSUE TITLE
OpenSSL 3.0.13, cannot install to calibre

### ISSUE THREAD

**Issue by muelli01** [Leseratte10/acsm-calibre-plugin#100]
### Bug description

When using Mint 22 with OpenSSL 3.0.13 install of the latest release creates an error.
It seems the regex for detecting the version cannot handle this openssl version string as mentioned here:
https://github.com/NixOS/nixpkgs/blob/72b94272c96eef5fe866d10fd76544e54789759c/pkgs/development/python-modules/oscrypto/support-openssl-3.0.10.patch

edit: that is indeed the problem, after removing the plugin from ~/.config/calibre/plugins and patching the files, the plugin can be installed.

calibre, version 7.6.0
FEHLER: Unbehandelter Ausnahmefehler: <b>InvalidPlugin</b>:Initialisierung der Erweiterung Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/customize/ui.py", line 710, in initialize_plugin
    p.initialize()
  File "calibre_plugins.deacsm.__init__", line 226, in initialize
    from libadobe import createDeviceKeyFile, update_account_path, sendHTTPRequest
  File "/media/enc/Toolz/DeDRM Ebooks/DeACSM_0.0.16.zip/libadobe.py", line 59, in &lt;module&gt;
    from oscrypto import keys
  File "/home/USER/.config/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/keys.py", line 5, in &lt;module&gt;
    from ._asymmetric import parse_certificate, parse_private, parse_public
  File "/home/USER/.config/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/_asymmetric.py", line 27, in &lt;module&gt;
    from .kdf import pbkdf1, pbkdf2, pkcs12_kdf
  File "/home/USER/.config/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/kdf.py", line 9, in &lt;module&gt;
    from .util import rand_bytes
  File "/home/USER/.config/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/util.py", line 14, in &lt;module&gt;
    from ._openssl.util import rand_bytes
  File "/home/USER/.config/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/_openssl/util.py", line 6, in &lt;module&gt;
    from ._libcrypto import libcrypto, libcrypto_version_info, handle_openssl_error
  File "/home/USER/.config/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/_openssl/_libcrypto.py", line 24, in &lt;module&gt;
    from ._libcrypto_ctypes import (
  File "/home/USER/.config/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/_openssl/_libcrypto_ctypes.py", line 47, in &lt;module&gt;
    raise LibraryNotFoundError('Error detecting the version of libcrypto')
oscrypto.errors.LibraryNotFoundError: Error detecting the version of libcrypto
 fehlgeschlagen. Rückverfolgung:
Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/customize/ui.py", line 710, in initialize_plugin
    p.initialize()
  File "calibre_plugins.deacsm.__init__", line 226, in initialize
    from libadobe import createDeviceKeyFile, update_account_path, sendHTTPRequest
  File "/media/enc/Toolz/DeDRM Ebooks/DeACSM_0.0.16.zip/libadobe.py", line 59, in &lt;module&gt;
    from oscrypto import keys
  File "/home/USER/.config/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/keys.py", line 5, in &lt;module&gt;
    from ._asymmetric import parse_certificate, parse_private, parse_public
  File "/home/USER/.config/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/_asymmetric.py", line 27, in &lt;module&gt;
    from .kdf import pbkdf1, pbkdf2, pkcs12_kdf
  File "/home/USER/.config/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/kdf.py", line 9, in &lt;module&gt;
    from .util import rand_bytes
  File "/home/USER/.config/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/util.py", line 14, in &lt;module&gt;
    from ._openssl.util import rand_bytes
  File "/home/USER/.config/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/_openssl/util.py", line 6, in &lt;module&gt;
    from ._libcrypto import libcrypto, libcrypto_version_info, handle_openssl_error
  File "/home/USER/.config/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/_openssl/_libcrypto.py", line 24, in &lt;module&gt;
    from ._libcrypto_ctypes import (
  File "/home/USER/.config/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/_openssl/_libcrypto_ctypes.py", line 47, in &lt;module&gt;
    raise LibraryNotFoundError('Error detecting the version of libcrypto')
oscrypto.errors.LibraryNotFoundError: Error detecting the version of libcrypto

calibre 7.6  embedded-python: False
Linux-6.8.0-39-generic-x86_64-with-glibc2.39 Linux ('64bit', 'ELF')
('Linux', '6.8.0-39-generic', '#39-Ubuntu SMP PREEMPT_DYNAMIC Fri Jul  5 21:49:14 UTC 2024')
Python 3.12.3
Interface language: de
EXE path: /usr/bin/python3.12
Successfully initialized third party plugins: DeDRM (10, 0, 3)
Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/customize/ui.py", line 710, in initialize_plugin
    p.initialize()
  File "calibre_plugins.deacsm.__init__", line 226, in initialize
    from libadobe import createDeviceKeyFile, update_account_path, sendHTTPRequest
  File "/media/enc/Toolz/DeDRM Ebooks/DeACSM_0.0.16.zip/libadobe.py", line 59, in <module>
    from oscrypto import keys
  File "/home/USER/.config/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/keys.py", line 5, in <module>
    from ._asymmetric import parse_certificate, parse_private, parse_public
  File "/home/USER/.config/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/_asymmetric.py", line 27, in <module>
    from .kdf import pbkdf1, pbkdf2, pkcs12_kdf
  File "/home/USER/.config/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/kdf.py", line 9, in <module>
    from .util import rand_bytes
  File "/home/USER/.config/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/util.py", line 14, in <module>
    from ._openssl.util import rand_bytes
  File "/home/USER/.config/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/_openssl/util.py", line 6, in <module>
    from ._libcrypto import libcrypto, libcrypto_version_info, handle_openssl_error
  File "/home/USER/.config/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/_openssl/_libcrypto.py", line 24, in <module>
    from ._libcrypto_ctypes import (
  File "/home/USER/.config/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/_openssl/_libcrypto_ctypes.py", line 47, in <module>
    raise LibraryNotFoundError('Error detecting the version of libcrypto')
oscrypto.errors.LibraryNotFoundError: Error detecting the version of libcrypto

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/gui2/preferences/plugins.py", line 325, in add_plugin
    plugin = add_plugin(path)
             ^^^^^^^^^^^^^^^^
  File "/usr/lib/calibre/calibre/customize/ui.py", line 520, in add_plugin
    plugin = initialize_plugin(plugin, path_to_zip_file, PluginInstallationType.EXTERNAL)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/calibre/calibre/customize/ui.py", line 715, in initialize_plugin
    raise InvalidPlugin((_('Initialization of plugin %s failed with traceback:')
calibre.customize.InvalidPlugin: Initialisierung der Erweiterung Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/customize/ui.py", line 710, in initialize_plugin
    p.initialize()
  File "calibre_plugins.deacsm.__init__", line 226, in initialize
    from libadobe import createDeviceKeyFile, update_account_path, sendHTTPRequest
  File "/media/enc/Toolz/DeDRM Ebooks/DeACSM_0.0.16.zip/libadobe.py", line 59, in <module>
    from oscrypto import keys
  File "/home/USER/.config/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/keys.py", line 5, in <module>
    from ._asymmetric import parse_certificate, parse_private, parse_public
  File "/home/USER/.config/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/_asymmetric.py", line 27, in <module>
    from .kdf import pbkdf1, pbkdf2, pkcs12_kdf
  File "/home/USER/.config/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/kdf.py", line 9, in <module>
    from .util import rand_bytes
  File "/home/USER/.config/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/util.py", line 14, in <module>
    from ._openssl.util import rand_bytes
  File "/home/USER/.config/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/_openssl/util.py", line 6, in <module>
    from ._libcrypto import libcrypto, libcrypto_version_info, handle_openssl_error
  File "/home/USER/.config/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/_openssl/_libcrypto.py", line 24, in <module>
    from ._libcrypto_ctypes import (
  File "/home/USER/.config/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/_openssl/_libcrypto_ctypes.py", line 47, in <module>
    raise LibraryNotFoundError('Error detecting the version of libcrypto')
oscrypto.errors.LibraryNotFoundError: Error detecting the version of libcrypto
 fehlgeschlagen. Rückverfolgung:
Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/customize/ui.py", line 710, in initialize_plugin
    p.initialize()
  File "calibre_plugins.deacsm.__init__", line 226, in initialize
    from libadobe import createDeviceKeyFile, update_account_path, sendHTTPRequest
  File "/media/enc/Toolz/DeDRM Ebooks/DeACSM_0.0.16.zip/libadobe.py", line 59, in <module>
    from oscrypto import keys
  File "/home/USER/.config/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/keys.py", line 5, in <module>
    from ._asymmetric import parse_certificate, parse_private, parse_public
  File "/home/USER/.config/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/_asymmetric.py", line 27, in <module>
    from .kdf import pbkdf1, pbkdf2, pkcs12_kdf
  File "/home/USER/.config/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/kdf.py", line 9, in <module>
    from .util import rand_bytes
  File "/home/USER/.config/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/util.py", line 14, in <module>
    from ._openssl.util import rand_bytes
  File "/home/USER/.config/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/_openssl/util.py", line 6, in <module>
    from ._libcrypto import libcrypto, libcrypto_version_info, handle_openssl_error
  File "/home/USER/.config/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/_openssl/_libcrypto.py", line 24, in <module>
    from ._libcrypto_ctypes import (
  File "/home/USER/.config/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/_openssl/_libcrypto_ctypes.py", line 47, in <module>
    raise LibraryNotFoundError('Error detecting the version of libcrypto')
oscrypto.errors.LibraryNotFoundError: Error detecting the version of libcrypto

### Operating system

Linux

### Which version of Calibre are you running?

7.6.0

### Which version of the ACSM Input plugin are you running?

v0.0.16

**Comment by Leseratte10** [comment]
This is an issue in 0.0.16 that's already fixed in the latest beta, unfortunately I still haven't had time to turn that into a proper release version. 

Try installing the beta from https://github.com/Leseratte10/acsm-calibre-plugin/actions/runs/10280358906/artifacts/1784495838 and see if that fixes the issue for you. Make sure to make a backup of your activation data beforehand just in case.

**Comment by baeuchle** [comment]
This link doesn't work anymore.

**Comment by baeuchle** [comment]
Well, it works now. Strange. Apologies. Doesn't work, though, but that will be in a different bug shortly.
