### ISSUE TITLE
Unable to install Plugin on Mac

### ISSUE THREAD

**Issue by dunxd** [Leseratte10/acsm-calibre-plugin#106]
### Bug description

Attempted to install the plugin to Calibre 7.18 on macOS Sonoma in the following ways:

* Through Preferences > Plugins > Get new plugins > searchfor acsm and then install
* Download 0.0.16 zip from this repo, then in Calibre Preferences > Plugins > Load plugin from file

Throws the same error in both cases:

```
calibre, version 7.18.0
ERROR: Install plugin failed: A problem occurred while installing this plugin. This plugin will now be uninstalled. Please post the error message in details below into the forum thread for this plugin and restart calibre.

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 722, in initialize_plugin
  File "calibre_plugins.deacsm.__init__", line 226, in initialize
    from libadobe import createDeviceKeyFile, update_account_path, sendHTTPRequest
  File "/var/folders/dz/wvb1lxq56wg_wk3ppwqw4mdc0000gn/C/calibre_7.18.0_tmp_65youd1e/g70hhux5.zip/libadobe.py", line 59, in <module>
    from oscrypto import keys
  File "/Users/[redacted]/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/keys.py", line 5, in <module>
    from ._asymmetric import parse_certificate, parse_private, parse_public
  File "/Users/[redacted]/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/_asymmetric.py", line 27, in <module>
    from .kdf import pbkdf1, pbkdf2, pkcs12_kdf
  File "/Users/[redacted]/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/kdf.py", line 9, in <module>
    from .util import rand_bytes
  File "/Users/[redacted]/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/util.py", line 10, in <module>
    from ._mac.util import rand_bytes
  File "/Users/[redacted]/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/_mac/util.py", line 208, in <module>
    from .._openssl._libcrypto import libcrypto
  File "/Users/[redacted]/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/_openssl/_libcrypto.py", line 24, in <module>
    from ._libcrypto_ctypes import (
  File "/Users/[redacted]/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/_openssl/_libcrypto_ctypes.py", line 30, in <module>
    libcrypto = CDLL(libcrypto_path, use_errno=True)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "ctypes/__init__.py", line 376, in __init__
OSError: dlopen(/usr/local/lib/libcrypto.dylib, 0x0006): tried: '/usr/local/lib/libcrypto.dylib' (code signature in <FE4CC808-DD03-3873-9906-B342484034D1> '/usr/local/Cellar/openssl@3/3.3.2/lib/libcrypto.3.dylib' not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/lib/libcrypto.dylib' (no such file), '/usr/local/lib/libcrypto.dylib' (code signature in <FE4CC808-DD03-3873-9906-B342484034D1> '/usr/local/Cellar/openssl@3/3.3.2/lib/libcrypto.3.dylib' not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.), '/usr/local/Cellar/openssl@3/3.3.2/lib/libcrypto.3.dylib' (code signature in <FE4CC808-DD03-3873-9906-B342484034D1> '/usr/local/Cellar/openssl@3/3.3.2/lib/libcrypto.3.dylib' not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/Cellar/openssl@3/3.3.2/lib/libcrypto.3.dylib' (no such file), '/usr/local/Cellar/openssl@3/3.3.2/lib/libcrypto.3.dylib' (code signature in <FE4CC808-DD03-3873-9906-B342484034D1> '/usr/local/Cellar/openssl@3/3.3.2/lib/libcrypto.3.dylib' not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/gui2/dialogs/plugin_updater.py", line 742, in _install_clicked
  File "calibre/customize/ui.py", line 532, in add_plugin
  File "calibre/customize/ui.py", line 727, in initialize_plugin
calibre.customize.InvalidPlugin: Initialization of plugin Traceback (most recent call last):
  File "calibre/customize/ui.py", line 722, in initialize_plugin
  File "calibre_plugins.deacsm.__init__", line 226, in initialize
    from libadobe import createDeviceKeyFile, update_account_path, sendHTTPRequest
  File "/var/folders/dz/wvb1lxq56wg_wk3ppwqw4mdc0000gn/C/calibre_7.18.0_tmp_65youd1e/g70hhux5.zip/libadobe.py", line 59, in <module>
    from oscrypto import keys
  File "/Users/[redacted]/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/keys.py", line 5, in <module>
    from ._asymmetric import parse_certificate, parse_private, parse_public
  File "/Users/[redacted]/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/_asymmetric.py", line 27, in <module>
    from .kdf import pbkdf1, pbkdf2, pkcs12_kdf
  File "/Users/[redacted]/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/kdf.py", line 9, in <module>
    from .util import rand_bytes
  File "/Users/[redacted]/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/util.py", line 10, in <module>
    from ._mac.util import rand_bytes
  File "/Users/[redacted]/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/_mac/util.py", line 208, in <module>
    from .._openssl._libcrypto import libcrypto
  File "/Users/[redacted]/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/_openssl/_libcrypto.py", line 24, in <module>
    from ._libcrypto_ctypes import (
  File "/Users/[redacted]/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/_openssl/_libcrypto_ctypes.py", line 30, in <module>
    libcrypto = CDLL(libcrypto_path, use_errno=True)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "ctypes/__init__.py", line 376, in __init__
OSError: dlopen(/usr/local/lib/libcrypto.dylib, 0x0006): tried: '/usr/local/lib/libcrypto.dylib' (code signature in <FE4CC808-DD03-3873-9906-B342484034D1> '/usr/local/Cellar/openssl@3/3.3.2/lib/libcrypto.3.dylib' not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/lib/libcrypto.dylib' (no such file), '/usr/local/lib/libcrypto.dylib' (code signature in <FE4CC808-DD03-3873-9906-B342484034D1> '/usr/local/Cellar/openssl@3/3.3.2/lib/libcrypto.3.dylib' not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.), '/usr/local/Cellar/openssl@3/3.3.2/lib/libcrypto.3.dylib' (code signature in <FE4CC808-DD03-3873-9906-B342484034D1> '/usr/local/Cellar/openssl@3/3.3.2/lib/libcrypto.3.dylib' not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/Cellar/openssl@3/3.3.2/lib/libcrypto.3.dylib' (no such file), '/usr/local/Cellar/openssl@3/3.3.2/lib/libcrypto.3.dylib' (code signature in <FE4CC808-DD03-3873-9906-B342484034D1> '/usr/local/Cellar/openssl@3/3.3.2/lib/libcrypto.3.dylib' not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.)
 failed with traceback:
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 722, in initialize_plugin
  File "calibre_plugins.deacsm.__init__", line 226, in initialize
    from libadobe import createDeviceKeyFile, update_account_path, sendHTTPRequest
  File "/var/folders/dz/wvb1lxq56wg_wk3ppwqw4mdc0000gn/C/calibre_7.18.0_tmp_65youd1e/g70hhux5.zip/libadobe.py", line 59, in <module>
    from oscrypto import keys
  File "/Users/[redacted]/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/keys.py", line 5, in <module>
    from ._asymmetric import parse_certificate, parse_private, parse_public
  File "/Users/[redacted]/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/_asymmetric.py", line 27, in <module>
    from .kdf import pbkdf1, pbkdf2, pkcs12_kdf
  File "/Users/[redacted]/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/kdf.py", line 9, in <module>
    from .util import rand_bytes
  File "/Users/[redacted]/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/util.py", line 10, in <module>
    from ._mac.util import rand_bytes
  File "/Users/[redacted]/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/_mac/util.py", line 208, in <module>
    from .._openssl._libcrypto import libcrypto
  File "/Users/[redacted]/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/_openssl/_libcrypto.py", line 24, in <module>
    from ._libcrypto_ctypes import (
  File "/Users/[redacted]/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/_openssl/_libcrypto_ctypes.py", line 30, in <module>
    libcrypto = CDLL(libcrypto_path, use_errno=True)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "ctypes/__init__.py", line 376, in __init__
OSError: dlopen(/usr/local/lib/libcrypto.dylib, 0x0006): tried: '/usr/local/lib/libcrypto.dylib' (code signature in <FE4CC808-DD03-3873-9906-B342484034D1> '/usr/local/Cellar/openssl@3/3.3.2/lib/libcrypto.3.dylib' not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/lib/libcrypto.dylib' (no such file), '/usr/local/lib/libcrypto.dylib' (code signature in <FE4CC808-DD03-3873-9906-B342484034D1> '/usr/local/Cellar/openssl@3/3.3.2/lib/libcrypto.3.dylib' not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.), '/usr/local/Cellar/openssl@3/3.3.2/lib/libcrypto.3.dylib' (code signature in <FE4CC808-DD03-3873-9906-B342484034D1> '/usr/local/Cellar/openssl@3/3.3.2/lib/libcrypto.3.dylib' not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/Cellar/openssl@3/3.3.2/lib/libcrypto.3.dylib' (no such file), '/usr/local/Cellar/openssl@3/3.3.2/lib/libcrypto.3.dylib' (code signature in <FE4CC808-DD03-3873-9906-B342484034D1> '/usr/local/Cellar/openssl@3/3.3.2/lib/libcrypto.3.dylib' not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.)

```

### Operating system

MacOS

### Which version of Calibre are you running?

7.18.0

### Which version of the ACSM Input plugin are you running?

v0.0.16

**Comment by Constantin1489** [comment]
See also https://github.com/Leseratte10/acsm-calibre-plugin/issues/63#issuecomment-1688899240

**Comment by dunxd** [comment]
Just to clarify - do you mean `brew unlink openssl@3` then install the plugin followed by `brew link openssl@3` or do you mean `unlink` then immediately `link` openssl somehow resolves the issue?

**Comment by Constantin1489** [comment]
`brew unlink openssl@3` -> install plugin -> ??? -> profit -> `brew link openssl@3`
Yes.

**Comment by DashingDave** [comment]
I have the same issue, but `brew unlink openss1@3` gives me `Error: No such keg: /usr/local/Cellar/openss1@3`, so I apparently don't even have such a thing installed and the plugin fails to install:

`calibre, version 7.20.0
ERROR: Install plugin failed: A problem occurred while installing this plugin. This plugin will now be uninstalled. Please post the error message in details below into the forum thread for this plugin and restart calibre.

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 724, in initialize_plugin
  File "calibre_plugins.deacsm.__init__", line 226, in initialize
    from libadobe import createDeviceKeyFile, update_account_path, sendHTTPRequest
  File "/var/folders/50/ckcsb8t176d5zwc88bpr4l5w0000gn/C/calibre_7.20.0_tmp_63g9twja/7cl2b6lr.zip/libadobe.py", line 59, in <module>
    from oscrypto import keys
  File "/Users/dashingdave/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/keys.py", line 5, in <module>
    from ._asymmetric import parse_certificate, parse_private, parse_public
  File "/Users/dashingdave/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/_asymmetric.py", line 27, in <module>
    from .kdf import pbkdf1, pbkdf2, pkcs12_kdf
  File "/Users/dashingdave/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/kdf.py", line 9, in <module>
    from .util import rand_bytes
  File "/Users/dashingdave/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/util.py", line 10, in <module>
    from ._mac.util import rand_bytes
  File "/Users/dashingdave/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/_mac/util.py", line 208, in <module>
    from .._openssl._libcrypto import libcrypto
  File "/Users/dashingdave/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/_openssl/_libcrypto.py", line 24, in <module>
    from ._libcrypto_ctypes import (
  File "/Users/dashingdave/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/_openssl/_libcrypto_ctypes.py", line 30, in <module>
    libcrypto = CDLL(libcrypto_path, use_errno=True)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "ctypes/__init__.py", line 376, in __init__
OSError: dlopen(/usr/local/lib/libcrypto.dylib, 0x0006): tried: '/usr/local/lib/libcrypto.dylib' (code signature in <2408EF3F-918D-3BCB-ADB7-F7DE7EDFE1C7> '/usr/local/Cellar/openssl@3/3.3.1/lib/libcrypto.3.dylib' not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/lib/libcrypto.dylib' (no such file), '/usr/local/lib/libcrypto.dylib' (code signature in <2408EF3F-918D-3BCB-ADB7-F7DE7EDFE1C7> '/usr/local/Cellar/openssl@3/3.3.1/lib/libcrypto.3.dylib' not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.), '/usr/local/Cellar/openssl@3/3.3.1/lib/libcrypto.3.dylib' (code signature in <2408EF3F-918D-3BCB-ADB7-F7DE7EDFE1C7> '/usr/local/Cellar/openssl@3/3.3.1/lib/libcrypto.3.dylib' not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/Cellar/openssl@3/3.3.1/lib/libcrypto.3.dylib' (no such file), '/usr/local/Cellar/openssl@3/3.3.1/lib/libcrypto.3.dylib' (code signature in <2408EF3F-918D-3BCB-ADB7-F7DE7EDFE1C7> '/usr/local/Cellar/openssl@3/3.3.1/lib/libcrypto.3.dylib' not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/gui2/dialogs/plugin_updater.py", line 742, in _install_clicked
  File "calibre/customize/ui.py", line 534, in add_plugin
  File "calibre/customize/ui.py", line 729, in initialize_plugin
calibre.customize.InvalidPlugin: Initialization of plugin Traceback (most recent call last):
  File "calibre/customize/ui.py", line 724, in initialize_plugin
  File "calibre_plugins.deacsm.__init__", line 226, in initialize
    from libadobe import createDeviceKeyFile, update_account_path, sendHTTPRequest
  File "/var/folders/50/ckcsb8t176d5zwc88bpr4l5w0000gn/C/calibre_7.20.0_tmp_63g9twja/7cl2b6lr.zip/libadobe.py", line 59, in <module>
    from oscrypto import keys
  File "/Users/dashingdave/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/keys.py", line 5, in <module>
    from ._asymmetric import parse_certificate, parse_private, parse_public
  File "/Users/dashingdave/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/_asymmetric.py", line 27, in <module>
    from .kdf import pbkdf1, pbkdf2, pkcs12_kdf
  File "/Users/dashingdave/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/kdf.py", line 9, in <module>
    from .util import rand_bytes
  File "/Users/dashingdave/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/util.py", line 10, in <module>
    from ._mac.util import rand_bytes
  File "/Users/dashingdave/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/_mac/util.py", line 208, in <module>
    from .._openssl._libcrypto import libcrypto
  File "/Users/dashingdave/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/_openssl/_libcrypto.py", line 24, in <module>
    from ._libcrypto_ctypes import (
  File "/Users/dashingdave/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/_openssl/_libcrypto_ctypes.py", line 30, in <module>
    libcrypto = CDLL(libcrypto_path, use_errno=True)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "ctypes/__init__.py", line 376, in __init__
OSError: dlopen(/usr/local/lib/libcrypto.dylib, 0x0006): tried: '/usr/local/lib/libcrypto.dylib' (code signature in &lt;2408EF3F-918D-3BCB-ADB7-F7DE7EDFE1C7&gt; '/usr/local/Cellar/openssl@3/3.3.1/lib/libcrypto.3.dylib' not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/lib/libcrypto.dylib' (no such file), '/usr/local/lib/libcrypto.dylib' (code signature in &lt;2408EF3F-918D-3BCB-ADB7-F7DE7EDFE1C7&gt; '/usr/local/Cellar/openssl@3/3.3.1/lib/libcrypto.3.dylib' not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.), '/usr/local/Cellar/openssl@3/3.3.1/lib/libcrypto.3.dylib' (code signature in &lt;2408EF3F-918D-3BCB-ADB7-F7DE7EDFE1C7&gt; '/usr/local/Cellar/openssl@3/3.3.1/lib/libcrypto.3.dylib' not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/Cellar/openssl@3/3.3.1/lib/libcrypto.3.dylib' (no such file), '/usr/local/Cellar/openssl@3/3.3.1/lib/libcrypto.3.dylib' (code signature in &lt;2408EF3F-918D-3BCB-ADB7-F7DE7EDFE1C7&gt; '/usr/local/Cellar/openssl@3/3.3.1/lib/libcrypto.3.dylib' not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.)`

Installing from a zip file gives a slightly different error:

`calibre 7.20  embedded-python: True
macOS-13.7-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '22.6.0', 'Darwin Kernel Version 22.6.0: Wed Jul 31 21:42:48 PDT 2024; root:xnu-8796.141.3.707.4~1/RELEASE_X86_64')
Python 3.11.5
OSX: ('13.7', ('', '', ''), 'x86_64')
Interface language: None
EXE path: /Applications/calibre.app/Contents/MacOS/calibre
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 16, 0) && DeDRM (10, 0, 9) && Package KFX (from KFX Input) (2, 16, 0) && KFX metadata reader (from KFX Input) (2, 16, 0) && From KFX (2, 16, 0) && KFX Input (2, 16, 0) && OverDrive Libby (0, 1, 9, 1) && PDF Cover (0, 1, 0) && Prettify Cover (1, 6, 0)
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 724, in initialize_plugin
  File "calibre_plugins.deacsm.__init__", line 226, in initialize
    from libadobe import createDeviceKeyFile, update_account_path, sendHTTPRequest
  File "/Users/dashingdave/Downloads/DeACSM_0.0.16.zip/libadobe.py", line 59, in <module>
    from oscrypto import keys
  File "/Users/dashingdave/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/keys.py", line 5, in <module>
    from ._asymmetric import parse_certificate, parse_private, parse_public
  File "/Users/dashingdave/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/_asymmetric.py", line 27, in <module>
    from .kdf import pbkdf1, pbkdf2, pkcs12_kdf
  File "/Users/dashingdave/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/kdf.py", line 9, in <module>
    from .util import rand_bytes
  File "/Users/dashingdave/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/util.py", line 10, in <module>
    from ._mac.util import rand_bytes
  File "/Users/dashingdave/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/_mac/util.py", line 208, in <module>
    from .._openssl._libcrypto import libcrypto
  File "/Users/dashingdave/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/_openssl/_libcrypto.py", line 24, in <module>
    from ._libcrypto_ctypes import (
  File "/Users/dashingdave/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/_openssl/_libcrypto_ctypes.py", line 30, in <module>
    libcrypto = CDLL(libcrypto_path, use_errno=True)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "ctypes/__init__.py", line 376, in __init__
OSError: dlopen(/usr/local/lib/libcrypto.dylib, 0x0006): tried: '/usr/local/lib/libcrypto.dylib' (code signature in <2408EF3F-918D-3BCB-ADB7-F7DE7EDFE1C7> '/usr/local/Cellar/openssl@3/3.3.1/lib/libcrypto.3.dylib' not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/lib/libcrypto.dylib' (no such file), '/usr/local/lib/libcrypto.dylib' (code signature in <2408EF3F-918D-3BCB-ADB7-F7DE7EDFE1C7> '/usr/local/Cellar/openssl@3/3.3.1/lib/libcrypto.3.dylib' not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.), '/usr/local/Cellar/openssl@3/3.3.1/lib/libcrypto.3.dylib' (code signature in <2408EF3F-918D-3BCB-ADB7-F7DE7EDFE1C7> '/usr/local/Cellar/openssl@3/3.3.1/lib/libcrypto.3.dylib' not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/Cellar/openssl@3/3.3.1/lib/libcrypto.3.dylib' (no such file), '/usr/local/Cellar/openssl@3/3.3.1/lib/libcrypto.3.dylib' (code signature in <2408EF3F-918D-3BCB-ADB7-F7DE7EDFE1C7> '/usr/local/Cellar/openssl@3/3.3.1/lib/libcrypto.3.dylib' not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/gui2/preferences/plugins.py", line 322, in add_plugin
  File "calibre/customize/ui.py", line 534, in add_plugin
  File "calibre/customize/ui.py", line 729, in initialize_plugin
calibre.customize.InvalidPlugin: Initialization of plugin Traceback (most recent call last):
  File "calibre/customize/ui.py", line 724, in initialize_plugin
  File "calibre_plugins.deacsm.__init__", line 226, in initialize
    from libadobe import createDeviceKeyFile, update_account_path, sendHTTPRequest
  File "/Users/dashingdave/Downloads/DeACSM_0.0.16.zip/libadobe.py", line 59, in <module>
    from oscrypto import keys
  File "/Users/dashingdave/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/keys.py", line 5, in <module>
    from ._asymmetric import parse_certificate, parse_private, parse_public
  File "/Users/dashingdave/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/_asymmetric.py", line 27, in <module>
    from .kdf import pbkdf1, pbkdf2, pkcs12_kdf
  File "/Users/dashingdave/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/kdf.py", line 9, in <module>
    from .util import rand_bytes
  File "/Users/dashingdave/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/util.py", line 10, in <module>
    from ._mac.util import rand_bytes
  File "/Users/dashingdave/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/_mac/util.py", line 208, in <module>
    from .._openssl._libcrypto import libcrypto
  File "/Users/dashingdave/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/_openssl/_libcrypto.py", line 24, in <module>
    from ._libcrypto_ctypes import (
  File "/Users/dashingdave/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/_openssl/_libcrypto_ctypes.py", line 30, in <module>
    libcrypto = CDLL(libcrypto_path, use_errno=True)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by Constantin1489** [comment]
It's 'openssl' not with one('1')

**Comment by DashingDave** [comment]
🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️

**Comment by akemi12** [comment]
When I use "brew unlink openssl@3" it allows me to install the plugin. I restart calibre and it's listed under my plugins. When I do "brew link openssl@3" which was suggested above, the plugin disappears.

**Comment by fredowski** [comment]
I have the same problem on MacOS 12.6.7 with calibre 6.29.0 and DeACSM 0.0.16. I also use brew where I have openssl installed. I could install DeACSM and load ACSM files by 

1. mv /usr/local/lib /usr/local/lib-orig (I guess the same effect as brew unlink openssl)
2. Install DeACSM

When I rename /usr/local/lib-orig back to /usr/local/lib, then the plugin does not work anymore. When I drag&drop an ACSM file to calibre, then epub is not downloaded.
