### ISSUE TITLE
Error Returning Books

### ISSUE THREAD

**Issue by Topaz-55** [Leseratte10/acsm-calibre-plugin#108]
### Bug description

I cannot return two loaned books to the library and attempting to open 'Showed loaned books' results in the following error

calibre, version 7.17.0
ERROR: Unhandled exception: <b>TypeError</b>:unsupported operand type(s) for +: 'NoneType' and 'str'

calibre 7.17  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.11.5
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre.exe
Successfully initialized third party plugins: DeACSM (0, 0, 16) && DeDRM (7, 2, 1) && KePub Input (3, 6, 6) && KePub Metadata Reader (3, 4, 3) && KePub Metadata Writer (3, 4, 3) && KePub Output (3, 6, 11) && KindleUnpack - The Plugin (0, 83, 1) && Kobo Utilities (2, 17, 1) && KoboTouchExtended (3, 6, 11)
Traceback (most recent call last):
  File "calibre_plugins.deacsm.config", line 1298, in show_rented_books
  File "calibre_plugins.deacsm.config", line 1321, in __init__
  File "calibre_plugins.deacsm.config", line 1398, in populate_list
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

### Operating system

Windows

### Which version of Calibre are you running?

7.17

### Which version of the ACSM Input plugin are you running?

v0.016

**Comment by Leseratte10** [comment]
This is a known issue with 0.0.16, can you try downloading the 0.1.0 beta?
https://github.com/Leseratte10/acsm-calibre-plugin/actions/runs/10907951375/artifacts/1943945980

**Comment by Topaz-55** [comment]
Thanks, should I uninstall 0.0.16 first or just install 0.1.0?

**Comment by azzywazzy** [comment]
Is there any update on this issue? I borrowed 3 books from my local library, and when I went to return one of the books, all 3 vanished from the "Show Loaned Books" pane and 2 of them still show as checked out by my library. 

If I borrow a new book and return it, rather than returning that named book, it returns the oldest checked-out book that I currently have.

**Comment by Leseratte10** [comment]
Unfortunately I haven't had much time in the past to work on the plugin so 0.1.0 is still in beta because the automatic upgrade path from 0.0.16 to 0.1.0 is still broken. 

If you regularly use the return feature you can make a backup of your authorization, remove the plugin, restart calibre twice, then install the 0.1.0 version and import the backup again, and then it should work without issues.

**Comment by azzywazzy** [comment]
I'll give that a go. The link to download the beta above no longer works, and I can't see it anywhere in the list of releases - is there an easier way to access it? Thank so much!
