### ISSUE TITLE
libadobe module not found

### ISSUE THREAD

**Issue by Untel00** [Leseratte10/acsm-calibre-plugin#113]
### Bug description

Could not install DEACSM plugin in Caliber running under Windows. Tried with version 6.27, 6.29, 7.10 and 7.29 of Caliber with same results.

Also tried under Ubuntu 22.04.5 and instalation went on without problem and plugin is working correctly. 

calibre, version 6.27.0
ERREUR : Exception non gérée: <b>InvalidPlugin</b>:L’initialisation de l'extension Traceback (most recent call last):
  File "calibre\customize\ui.py", line 710, in initialize_plugin
  File "calibre_plugins.deacsm.__init__", line 307, in initialize
ModuleNotFoundError: No module named 'libadobe'
 a échoué avec traceback :
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 710, in initialize_plugin
  File "calibre_plugins.deacsm.__init__", line 307, in initialize
ModuleNotFoundError: No module named 'libadobe'

calibre 6.27  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.10.1
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: fr
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 710, in initialize_plugin
  File "calibre_plugins.deacsm.__init__", line 307, in initialize
ModuleNotFoundError: No module named 'libadobe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\gui2\preferences\plugins.py", line 325, in add_plugin
  File "calibre\customize\ui.py", line 520, in add_plugin
  File "calibre\customize\ui.py", line 715, in initialize_plugin
calibre.customize.InvalidPlugin: L’initialisation de l'extension Traceback (most recent call last):
  File "calibre\customize\ui.py", line 710, in initialize_plugin
  File "calibre_plugins.deacsm.__init__", line 307, in initialize
ModuleNotFoundError: No module named 'libadobe'
 a échoué avec traceback :
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 710, in initialize_plugin
  File "calibre_plugins.deacsm.__init__", line 307, in initialize
ModuleNotFoundError: No module named 'libadobe'

  

### Operating system

Windows

### Which version of Calibre are you running?

7.29

### Which version of the ACSM Input plugin are you running?

v0.0.16 (Downloaded from github)

### Further information

Maybe libadobe dll file is missing in package (DEDRM do have dll file for Crypto).

**Comment by Leseratte10** [comment]
Libadobe is not a DLL file, it's a python script, and it's included in the plugin. 

Can you try the latest beta [here](https://github.com/Leseratte10/acsm-calibre-plugin/actions/runs/12741834382/artifacts/2420369752) and see if that works?

**Comment by Untel00** [comment]
Sorry to be late to respond.
Tried the Beta version and everything is back to normal.
Thanks

**Comment by firewuf** [comment]
@Leseratte10 Do you think you could send a new link to that beta version again? I'm having the same issue and the download link to the beta version is a dead link. Thanks for the work you do!

**Comment by thematthew1** [comment]
@firewuf, I hope this helps: https://github.com/Leseratte10/acsm-calibre-plugin/actions/runs/14431491679/workflow

follow that workflow by hand any you can build from source pretty easy
