### ISSUE TITLE
plug-in installation fails

### ISSUE THREAD

**Issue by kingaa** [Leseratte10/acsm-calibre-plugin#17]
### Bug description

I attempted to install the plugin by first downloading the plugin zip file from the github release.  I got the error message below.  I also attempted to install from an interactive calibre session, which also resulted in this error.

### Operating system

Linux

### Which version of Calibre are you running?

5.35.0

### Which version of the DeACSM plugin are you running?

v0.0.15

### Further information

calibre, version 5.35.0
ERROR: Install plugin failed: A problem occurred while installing this plugin. This plugin will now be uninstalled. Please post the error message in details below into the forum thread for this plugin and restart calibre.

Traceback (most recent call last):
  File "calibre_plugins.deacsm.__init__", line 125, in initialize
    print("Module update from \"{0}\" to \"{1}\", extracting ...".format(id, id_plugin))
OSError: [Errno 5] Input/output error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 673, in initialize_plugin
  File "calibre_plugins.deacsm.__init__", line 204, in initialize
    traceback.print_exc()
  File "traceback.py", line 163, in print_exc
  File "traceback.py", line 105, in print_exception
OSError: [Errno 5] Input/output error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/gui2/dialogs/plugin_updater.py", line 712, in _install_clicked
  File "calibre/customize/ui.py", line 483, in add_plugin
  File "calibre/customize/ui.py", line 676, in initialize_plugin
OSError: [Errno 5] Input/output error

**Comment by kingaa** [comment]
Sorry, the problem goes away with an update of calibre.
