### ISSUE TITLE
Cannot decode ACSM file with calibre

### ISSUE THREAD

**Issue by jellejans** [Leseratte10/acsm-calibre-plugin#19]
Hi, 

I'm not able to convert ACSM to epub file in calibre. I tried the Adobe test files and they work as expected. File is converted to epub.
i'm getting this error in the logfile. 

Running file type plugin DeACSM failed with traceback:
Traceback (most recent call last):
  File "urllib\request.py", line 1350, in do_open
  File "http\client.py", line 1255, in request
  File "http\client.py", line 1301, in _send_request
  File "http\client.py", line 1250, in endheaders
  File "http\client.py", line 1010, in _send_output
  File "http\client.py", line 950, in send
  File "http\client.py", line 921, in connect
  File "socket.py", line 787, in create_connection
  File "socket.py", line 918, in getaddrinfo
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 175, in _run_filetype_plugins
  File "calibre_plugins.deacsm.__init__", line 378, in run
  File "calibre_plugins.deacsm.libadobeFulfill", line 420, in fulfill
  File "calibre_plugins.deacsm.libadobeFulfill", line 674, in performFulfillmentNotification
  File "calibre_plugins.deacsm.libadobe", line 307, in sendRequestDocuRC
  File "calibre_plugins.deacsm.libadobe", line 274, in sendPOSTHTTPRequest
  File "urllib\request.py", line 222, in urlopen
  File "urllib\request.py", line 525, in open
  File "urllib\request.py", line 542, in _open
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 1379, in http_open
  File "urllib\request.py", line 1353, in do_open
urllib.error.URLError: <urlopen error [Errno 11001] getaddrinfo failed>
DeACSM v0.0.15: Trying to parse file URLLink.acsm
DeACSM v0.0.15: Try to fulfill ...

Operating system
Windows

Which version of Calibre are you running?
5.41

Which version of the DeACSM plugin are you running?
0.0.15

Further information
No response

**Comment by jellejans** [comment]
Yes it's working now thanks !. Calibre generates the epub file, but now dedrm is not removing the DRM. I logged the issue on their github page.

**Comment by Leseratte10** [comment]
Thanks for testing. DRM removal not working is not related to this plugin, so I'm going to close this issue as the main bug has been fixed.

**Comment by racismbadkillneegeers** [comment]
THANK YOU SOMUCH I FUCKING LOVE YOU!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
