### ISSUE TITLE
Error when trying to add plugin to Calibre

### ISSUE THREAD

**Issue by Hellmark** [Leseratte10/acsm-calibre-plugin#2]
So, when I go to add the plugin through normal means, I get the following error

`calibre, version 5.25.0
ERROR: Unhandled exception: <b>InvalidPlugin</b>:Initialization of plugin Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/customize/ui.py", line 674, in initialize_plugin
    p.initialize()
  File "calibre_plugins.deacsm.__init__", line 138, in initialize
    update_account_path(deacsmprefs["path_to_account_data"])
UnboundLocalError: local variable 'update_account_path' referenced before assignment
 failed with traceback:
Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/customize/ui.py", line 674, in initialize_plugin
    p.initialize()
  File "calibre_plugins.deacsm.__init__", line 138, in initialize
    update_account_path(deacsmprefs["path_to_account_data"])
UnboundLocalError: local variable 'update_account_path' referenced before assignment

calibre 5.25  embedded-python: False is64bit: True
Linux-5.13.0-16-generic-x86_64-with-glibc2.34 Linux ('64bit', 'ELF')
('Linux', '5.13.0-16-generic', '#16-Ubuntu SMP Fri Sep 3 14:53:27 UTC 2021')
Python 3.9.7
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 2, 1) && Obok DeDRM (7, 2, 1)
Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/customize/ui.py", line 674, in initialize_plugin
    p.initialize()
  File "calibre_plugins.deacsm.__init__", line 138, in initialize
    update_account_path(deacsmprefs["path_to_account_data"])
UnboundLocalError: local variable 'update_account_path' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/gui2/preferences/plugins.py", line 327, in add_plugin
    plugin = add_plugin(path)
  File "/usr/lib/calibre/calibre/customize/ui.py", line 484, in add_plugin
    plugin = initialize_plugin(plugin, path_to_zip_file, PluginInstallationType.EXTERNAL)
  File "/usr/lib/calibre/calibre/customize/ui.py", line 679, in initialize_plugin
    raise InvalidPlugin((_('Initialization of plugin %s failed with traceback:')
calibre.customize.InvalidPlugin: Initialization of plugin Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/customize/ui.py", line 674, in initialize_plugin
    p.initialize()
  File "calibre_plugins.deacsm.__init__", line 138, in initialize
    update_account_path(deacsmprefs["path_to_account_data"])
UnboundLocalError: local variable 'update_account_path' referenced before assignment
 failed with traceback:
Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/customize/ui.py", line 674, in initialize_plugin
    p.initialize()
  File "calibre_plugins.deacsm.__init__", line 138, in initialize
    update_account_path(deacsmprefs["path_to_account_data"])
UnboundLocalError: local variable 'update_account_path' referenced before assignment
`

Running Kubuntu 21.10, with Calibre 5.25.0

**Comment by Hellmark** [comment]
100% fresh install. I just installed Kubuntu this week, and installed calibre yesterday. Hadn't migrated over any of my stuff yet.

It doesn't show up after install fails.
