### ISSUE TITLE
Install plugin failed

### ISSUE THREAD

**Issue by laserbyte** [Leseratte10/acsm-calibre-plugin#21]
calibre, version 3.39.1
ERROR: Install plugin failed: A problem occurred while installing this plugin. This plugin will now be uninstalled. Please post the error message in details below into the forum thread for this plugin and restart calibre.

Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/gui2/dialogs/plugin_updater.py", line 726, in _install_clicked
    plugin = add_plugin(zip_path)
  File "/usr/lib/calibre/calibre/customize/ui.py", line 472, in add_plugin
    plugin = load_plugin(path_to_zip_file)
  File "/usr/lib/calibre/calibre/customize/ui.py", line 61, in load_plugin
    return loader.load(path_to_zip_file)
  File "/usr/lib/calibre/calibre/customize/zipplugin.py", line 200, in load
    reload(m)
  File "/usr/lib/calibre/calibre/customize/zipplugin.py", line 180, in load_module
    import_name), 'exec', dont_inherit=True)
  File "calibre_plugins.deacsm.__init__", line 243
    def download(self, replyData: str):
                                ^
SyntaxError: invalid syntax

**Comment by Leseratte10** [comment]
The plugin does not yet support Calibre versions older than 5. I'm working on getting it to work with Calibre 4, but I don't know if it'll will support the ancient Calibre 3.X versions. 

I would recommend updating to the newest version of Calibre.

**Comment by Leseratte10** [comment]
No response, I'm assuming that updating to Calibre 5 fixed this issue.
