### ISSUE TITLE
Combination of deACSM and deDRM creates blank pdf (DRM not removed)

### ISSUE THREAD

**Issue by SchmidL** [Leseratte10/acsm-calibre-plugin#40]
### Bug description

hi,

I just tried, as several suggested, to use deACSM plugin in combination with DeDRM from this repo.

Unfortunately this just loaded a blank pdf, as normally happend when loading a pdf from ADE without removing the DRM.

Also the log show that a IndexError in de DeDRM: index out of range is thrown.
But, When the ACSM is opend in ADE (with my Adobe ID) -> the PDF gets imported into calibre -> DeDRM removes the DRM.
What not works is:
- ACSM directly opened in calibre (anonymous auth)-> PDF gets downloaded by DeACSM > DeDRM cannot remove DRM
- ACSM directly opened in calibre (Adobe ID)-> PDF gets downloaded by DeACSM > DeDRM cannot remove DRM

Also when I then try to redownload the fulfilled PDF from deACSM, with my Adobe ID, it cannot be opened in ADE, as `E_LIC_ALREADY_FULFILLED_BY_ANOTHER_USER `

I asked already the DeDRM community for help, but I think something doesn't work with deACSM  https://github.com/noDRM/DeDRM_tools/issues/195

How can I help to find the bug?

### Operating system

MacOS

### Which version of Calibre are you running?

6.5.0

### Which version of the ACSM Input plugin are you running?

v0.0.16

### Further information

```
Using calibre Qt style: True
calibre Debug log
calibre 6.5  embedded-python: True
macOS-12.6-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '21.6.0', 'Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64')
Python 3.10.1
OSX: ('12.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeACSM (0, 0, 16) && DeDRM (10, 0, 3) && Find Duplicates (1, 9, 7)
calibre 6.5  embedded-python: True
macOS-12.6-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '21.6.0', 'Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64')
Python 3.10.1
OSX: ('12.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeACSM (0, 0, 16) && DeDRM (10, 0, 3) && Find Duplicates (1, 9, 7)
QPA platform: cocoa
devicePixelRatio: 1.0
logicalDpi: 72.0 x 72.0
physicalDpi: 72.00000108133152 x 72.00000108133152
[0.00] Starting up...
[0.03] Showing splash screen...
[0.27] splash screen shown
[0.27] Initializing db...
[0.35] db initialized
[0.35] Constructing main UI...
[1.35] main UI initialized...
[1.35] Hiding splash screen
Starting QuickView
[5.48] splash screen hidden
[5.48] Started up in 5.48 seconds with 2790 books
DeDRM v10.0.3: Trying to decrypt v4sj3lko.pdf
DeDRM v10.0.3: v4sj3lko.pdf is a PDF ebook with encryption EBX_HANDLER
DeDRM v10.0.3: v4sj3lko.pdf is a PDF ebook (EBX) for UUID 616bc716-fca7-4970-b104-491cd0ea2f98
DeDRM v10.0.3: Trying encryption key default_key
ebx_V is 4  and ebx_type is 6
length is 16 and len(bookkey) is 0
DeDRM v10.0.3: Exception when decrypting after 0.1 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 724, in PDFIneptDecrypt
    result = ineptpdf.decryptBook(userkey, path_to_ebook, of.name)
  File "/Users/lorenz/Library/Preferences/calibre/plugins/DeDRM.zip/ineptpdf.py", line 2286, in decryptBook
    serializer = PDFSerializer(inf, userkey, inept)
  File "/Users/lorenz/Library/Preferences/calibre/plugins/DeDRM.zip/ineptpdf.py", line 2094, in __init__
    doc.initialize(userkey, inept)
  File "/Users/lorenz/Library/Preferences/calibre/plugins/DeDRM.zip/ineptpdf.py", line 1253, in initialize
    return self.initialize_ebx_inept(password, docid, param)
  File "/Users/lorenz/Library/Preferences/calibre/plugins/DeDRM.zip/ineptpdf.py", line 1707, in initialize_ebx_inept
    print("bookkey[0] is %d" % bookkey[0])
IndexError: index out of range
DeDRM v10.0.3: Failed to decrypt with key default_key after 0.1 seconds
DeDRM v10.0.3: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
DeDRM v10.0.3: Found new key 'DeACSM_uuid_616bc716-fca7-4970-b104-491cd0ea2f98' in DeACSM plugin
DeDRM v10.0.3: Trying a new default key
ebx_V is 4  and ebx_type is 6
length is 16 and len(bookkey) is 0
DeDRM v10.0.3: Exception when decrypting after 0.3 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 795, in PDFIneptDecrypt
    result = ineptpdf.decryptBook(userkey, path_to_ebook, of.name)
  File "/Users/lorenz/Library/Preferences/calibre/plugins/DeDRM.zip/ineptpdf.py", line 2286, in decryptBook
    serializer = PDFSerializer(inf, userkey, inept)
  File "/Users/lorenz/Library/Preferences/calibre/plugins/DeDRM.zip/ineptpdf.py", line 2094, in __init__
    doc.initialize(userkey, inept)
  File "/Users/lorenz/Library/Preferences/calibre/plugins/DeDRM.zip/ineptpdf.py", line 1253, in initialize
    return self.initialize_ebx_inept(password, docid, param)
  File "/Users/lorenz/Library/Preferences/calibre/plugins/DeDRM.zip/ineptpdf.py", line 1707, in initialize_ebx_inept
    print("bookkey[0] is %d" % bookkey[0])
IndexError: index out of range
DeDRM v10.0.3: Failed to decrypt with new default key after 0.3 seconds
DeDRM v10.0.3: Trying a new default key
ebx_V is 4  and ebx_type is 6
length is 16 and len(bookkey) is 0
DeDRM v10.0.3: Exception when decrypting after 0.4 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 795, in PDFIneptDecrypt
    result = ineptpdf.decryptBook(userkey, path_to_ebook, of.name)
  File "/Users/lorenz/Library/Preferences/calibre/plugins/DeDRM.zip/ineptpdf.py", line 2286, in decryptBook
    serializer = PDFSerializer(inf, userkey, inept)
  File "/Users/lorenz/Library/Preferences/calibre/plugins/DeDRM.zip/ineptpdf.py", line 2094, in __init__
    doc.initialize(userkey, inept)
  File "/Users/lorenz/Library/Preferences/calibre/plugins/DeDRM.zip/ineptpdf.py", line 1253, in initialize
    return self.initialize_ebx_inept(password, docid, param)
  File "/Users/lorenz/Library/Preferences/calibre/plugins/DeDRM.zip/ineptpdf.py", line 1707, in initialize_ebx_inept
    print("bookkey[0] is %d" % bookkey[0])
IndexError: index out of range
DeDRM v10.0.3: Failed to decrypt with new default key after 0.4 seconds
DeDRM v10.0.3: Finished after 0.4 seconds
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 435, in get_file_type_metadata
  File "calibre/customize/builtins.py", line 324, in get_metadata
  File "calibre/ebooks/metadata/pdf.py", line 124, in get_metadata
ValueError: Could not read info dict from PDF
DeACSM v0.0.16: Trying to parse file GehirnGeist032022.acsm
DeACSM v0.0.16: Try to fulfill ...
Notifying server ...
Notifying server https://acs6.onleihe.de/fulfillment/FulfillmentNotification
Fulfillment notification successful.
Notifying optional server https://ws.onleihe.de/acs6-return
Fulfillment notification successful (204).
DeACSM v0.0.16: Downloading book ...
DeACSM v0.0.16: Loading book from https://dp1.onleihe.de/downloadprovider/epub/20220204/9d375dc8-1ed5-33b9-973d-276290acda70.pdf
Download took 3410 ms (HTTP 200)
That's a PDF file
DeACSM v0.0.16: Downloaded PDF, adding encryption config ...
Searching for startxref ...
Got startxref: 8883863
Found ENC after 5 attempts - took 1 ms
Found EBX after 2062 attempts - took 4 ms


Encryption handler:
<</Root 1 0 R/Info 5 0 R/Encrypt 2051 0 R/ID[<05339E570442487CB736AB79F76DDE58><A56123FCE4CBD0477D31148C634E625F>]/Size 2052>>
EBX handler:
<</EBX_PUBLISHER(Spektrum der Wissenschaft Verlagsgesellschaft mbH)/Filter/EBX_HANDLER/Length 128/ADEPT_ID(urn:uuid:a08ebdff-6bae-4a13-92c2-0ab28d1021ff)/V 4/EBX_TITLE(Gehirn & Geist \\\(03/2022\\\))/EBX_AUTHOR()>>
Trimmed encryption handler:
<</Root 1 0 R/Info 5 0 R/Encrypt 2051 0 R/ID[<05339E570442487CB736AB79F76DDE58><A56123FCE4CBD0477D31148C634E625F>]/Size 2052>>
Updated EBX handler not logged due to sensitive data
Whole DRM patching took 25 milliseconds.
DeACSM v0.0.16: File successfully fulfilled ...
DeACSM v0.0.16: Executing plugin DeDRM ...
DeACSM v0.0.16: Plugin returned nothing - skipping
Syntax Error: Couldn't find the 'EBX_HANDLER' security handler
pdfinfo errored out with return code: 1
```

**Comment by Leseratte10** [comment]
That's going to be tricky if it's not clear whether the issue is in my ACSM Input plugin or in the DeDRM plugin ...

So you took one ACSM file and downloaded it both through ADE and through my plugin, both authorized with the same AdobeID? Then you should have two PDF files with DRM (one from ADE and one from my plugin) that should be identical. 

In an ideal world the files would be 100% identical, but they should definitely be syntactically / semantically identical. 

So can you try disabling the DeDRM plugin so that it doesn't get into the way, then download the ACSM once with ADE and once with my plugin and see if the resulting PDF files are identical?

Or, if you want (since the files are encrypted anyways and unreadable for me without your key), you can also send the two files (PDF with DRM from ADE, and PDF with DRM from my plugin) to my email and I'll take a look: s4-tmp-pzr3shbn7525-github-acsm-40@leseratte10.de (that's a temporary email for this issue report which will be disabled afterwards).

If the two files are (very) different it might be a bug with my plugin. If they are mostly identical it's probably a DRM removal issue.

**Comment by Leseratte10** [comment]
I don't think this is an issue with my plugin. I've just downloaded this very book from archive.org and I can import it into Calibre just fine. 

Are you trying to open the resulting PDF in Calibre or in ADE? This is probably an issue with DRM removal.

**Comment by Leseratte10** [comment]
No further response, I'm assuming this is fixed and/or was indeed a bug with DRM removal. If not, please re-open.
