### ISSUE TITLE
OSError [Errno 5] I/O error when importing plugin

### ISSUE THREAD

**Issue by Geremia** [Leseratte10/acsm-calibre-plugin#42]
### Bug description

```calibre, version 6.9.0
ERROR: Unhandled exception: <b>OSError</b>:[Errno 5] Errore di input/output

calibre 6.9  embedded-python: True
Linux-5.19.17-x86_64-AMD_Ryzen_Threadripper_2990WX_32-Core_Processor-with-glibc2.36 Linux ('64bit', 'ELF')
('Linux', '5.19.17', '#1 SMP PREEMPT_DYNAMIC Mon Oct 24 13:00:29 CDT 2022')
Python 3.10.1
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 50, 0) && DeDRM (10, 0, 3) && Package KFX (from KFX Input) (1, 50, 0) && Audit Log (1, 0, 18) && Extract ISBN (1, 6, 0) && KFX metadata reader (from KFX Input) (1, 50, 0) && KFX Input (1, 50, 0)
Traceback (most recent call last):
  File "calibre_plugins.deacsm.__init__", line 155, in initialize
    print("Module update from \"{0}\" to \"{1}\", extracting ...".format(id, id_plugin))
OSError: [Errno 5] Errore di input/output

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 676, in initialize_plugin
  File "calibre_plugins.deacsm.__init__", line 236, in initialize
    traceback.print_exc()
  File "traceback.py", line 179, in print_exc
  File "traceback.py", line 121, in print_exception
OSError: [Errno 5] Errore di input/output

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/gui2/preferences/plugins.py", line 325, in add_plugin
  File "calibre/customize/ui.py", line 486, in add_plugin
  File "calibre/customize/ui.py", line 679, in initialize_plugin
OSError: [Errno 5] Errore di input/output
```

### Operating system

Linux

### Which version of Calibre are you running?

6.9.0

### Which version of the ACSM Input plugin are you running?

v0.0.16

**Comment by Leseratte10** [comment]
Interesting error, that seems to come from the operating system, not from my plugin. Is this a clean install or are you updating from a previous version of the plugin? 
Does the issue persist after rebooting the computer?
Does it persist when you try to uninstall the plugin, restart Calibre, then try to install it again?

**Comment by Geremia** [comment]
@Leseratte10 It ended up being some Calibre glitch.
