### ISSUE TITLE
Help with installation

### ISSUE THREAD

**Issue by p1nkyy** [Leseratte10/acsm-calibre-plugin#48]
### Bug description

Hi, my friend tried to install ACSM INput in Mac but keep failing. I gave her the beta version (the one after you fix PDF)

This is the log. What's left is ACSM Input Plugin GUI Extension which can't be uninstalled, only disabled. Thanks for your help.

calibre, version 6.11.0
ERROR: Unhandled exception: <b>InvalidPlugin</b>:Initialisation of plug-in Traceback (most recent call last):
  File "calibre/customize/ui.py", line 676, in initialize_plugin
  File "calibre_plugins.deacsm._init_", line 289, in initialize
    deacsmprefs = prefs.ACSMInput_Prefs()
  File "calibre_plugins.deacsm.prefs", line 58, in _init_
    raise Exception("Why does the account folder not exist?")
Exception: Why does the account folder not exist?
 failed with traceback:
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 676, in initialize_plugin
  File "calibre_plugins.deacsm._init_", line 289, in initialize
    deacsmprefs = prefs.ACSMInput_Prefs()
  File "calibre_plugins.deacsm.prefs", line 58, in _init_
    raise Exception("Why does the account folder not exist?")
Exception: Why does the account folder not exist?

calibre 6.11  embedded-python: True
macOS-10.15.7-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.6.0', 'Darwin Kernel Version 19.6.0: Tue Jun 21 21:18:39 PDT 2022; root:xnu-6153.141.66~1/RELEASE_X86_64')
Python 3.10.1
OSX: ('10.15.7', ('', '', ''), 'x86_64')
Interface language: en_GB
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 50, 0) && Package KFX (from KFX Input) (1, 50, 0) && EpubMerge (2, 7, 0) && EpubSplit (2, 8, 0) && KFX metadata reader (from KFX Input) (1, 50, 0) && KFX Input (1, 50, 0) && Set KFX metadata (from KFX Output) (1, 65, 0) && KFX Output (1, 65, 0) && KindleUnpack - The Plugin (0, 81, 5) && ACSM Input Plugin GUI Extension (0, 1, 0)
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 676, in initialize_plugin
  File "calibre_plugins.deacsm._init_", line 289, in initialize
    deacsmprefs = prefs.ACSMInput_Prefs()
  File "calibre_plugins.deacsm.prefs", line 58, in _init_
    raise Exception("Why does the account folder not exist?")
Exception: Why does the account folder not exist?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/gui2/preferences/plugins.py", line 325, in add_plugin
  File "calibre/customize/ui.py", line 486, in add_plugin
  File "calibre/customize/ui.py", line 681, in initialize_plugin
calibre.customize.InvalidPlugin: Initialisation of plug-in Traceback (most recent call last):
  File "calibre/customize/ui.py", line 676, in initialize_plugin
  File "calibre_plugins.deacsm._init_", line 289, in initialize
    deacsmprefs = prefs.ACSMInput_Prefs()
  File "calibre_plugins.deacsm.prefs", line 58, in _init_
    raise Exception("Why does the account folder not exist?")
Exception: Why does the account folder not exist?
 failed with traceback:
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 676, in initialize_plugin
  File "calibre_plugins.deacsm._init_", line 289, in initialize
    deacsmprefs = prefs.ACSMInput_Prefs()
  File "calibre_plugins.deacsm.prefs", line 58, in _init_
    raise Exception("Why does the account folder not exist?")
Exception: Why does the account folder not exist?

### Operating system

MacOS

### Which version of Calibre are you running?

6.11

### Which version of the ACSM Input plugin are you running?

v0.0.17

**Comment by Leseratte10** [comment]
That's an interesting error. I'd try removing the plugin completely (remove the ZIP and JSON files from the plugin folder if the UI doesn't let you remove it), then restart Calibre, then try to reinstall it and see if the issue still occurs.

**Comment by Leseratte10** [comment]
No response, I'm assuming removing and re-installing the plugin fixed it. 999354dde9963a2c5685e936718a1776c9bd7a38 should fix it for the future. If it's occurring again with the most recent version on `master` please comment again.
