### ISSUE TITLE
Error installing ACSM Input plugin (AttributeError: module 'calibre_plugins.deacsm.prefs' has no attribute 'DeACSM_Prefs')

### ISSUE THREAD

**Issue by lonniganseaweed** [Leseratte10/acsm-calibre-plugin#79]
### Bug description

When trying to install from the .zip generated by acsm-calibre-plugin-master/bundle_calibre_plugin.sh, I get the followign error, any help would be greatly appreciated:

calibre, version 7.3.0
ERROR: Unhandled exception: <b>InvalidPlugin</b>:Initialization of plugin Traceback (most recent call last):
  File "/usr/lib64/calibre/calibre/customize/ui.py", line 710, in initialize_plugin
    p.initialize()
  File "calibre_plugins.deacsm.__init__", line 232, in initialize
    deacsmprefs = prefs.DeACSM_Prefs()
                  ^^^^^^^^^^^^^^^^^^
AttributeError: module 'calibre_plugins.deacsm.prefs' has no attribute 'DeACSM_Prefs'
 failed with traceback:
Traceback (most recent call last):
  File "/usr/lib64/calibre/calibre/customize/ui.py", line 710, in initialize_plugin
    p.initialize()
  File "calibre_plugins.deacsm.__init__", line 232, in initialize
    deacsmprefs = prefs.DeACSM_Prefs()
                  ^^^^^^^^^^^^^^^^^^
AttributeError: module 'calibre_plugins.deacsm.prefs' has no attribute 'DeACSM_Prefs'

calibre 7.3  embedded-python: False
Linux-6.7.0-204.fsync.fc39.x86_64-x86_64-with-glibc2.38 Linux ('64bit', 'ELF')
('Linux', '6.7.0-204.fsync.fc39.x86_64', '#1 SMP PREEMPT_DYNAMIC TKG Wed Jan 17 09:24:55 UTC 2024')
Python 3.12.1
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 3)
Traceback (most recent call last):
  File "/usr/lib64/calibre/calibre/customize/ui.py", line 710, in initialize_plugin
    p.initialize()
  File "calibre_plugins.deacsm.__init__", line 232, in initialize
    deacsmprefs = prefs.DeACSM_Prefs()
                  ^^^^^^^^^^^^^^^^^^
AttributeError: module 'calibre_plugins.deacsm.prefs' has no attribute 'DeACSM_Prefs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/calibre/calibre/gui2/preferences/plugins.py", line 324, in add_plugin
    plugin = add_plugin(path)
             ^^^^^^^^^^^^^^^^
  File "/usr/lib64/calibre/calibre/customize/ui.py", line 520, in add_plugin
    plugin = initialize_plugin(plugin, path_to_zip_file, PluginInstallationType.EXTERNAL)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/calibre/calibre/customize/ui.py", line 715, in initialize_plugin
    raise InvalidPlugin((_('Initialization of plugin %s failed with traceback:')
calibre.customize.InvalidPlugin: Initialization of plugin Traceback (most recent call last):
  File "/usr/lib64/calibre/calibre/customize/ui.py", line 710, in initialize_plugin
    p.initialize()
  File "calibre_plugins.deacsm.__init__", line 232, in initialize
    deacsmprefs = prefs.DeACSM_Prefs()
                  ^^^^^^^^^^^^^^^^^^
AttributeError: module 'calibre_plugins.deacsm.prefs' has no attribute 'DeACSM_Prefs'
 failed with traceback:
Traceback (most recent call last):
  File "/usr/lib64/calibre/calibre/customize/ui.py", line 710, in initialize_plugin
    p.initialize()
  File "calibre_plugins.deacsm.__init__", line 232, in initialize
    deacsmprefs = prefs.DeACSM_Prefs()
                  ^^^^^^^^^^^^^^^^^^
AttributeError: module 'calibre_plugins.deacsm.prefs' has no attribute 'DeACSM_Prefs'

### Operating system

Linux

### Which version of Calibre are you running?

7.3

### Which version of the ACSM Input plugin are you running?

0.1.0

**Comment by AaronDavidSchneider** [comment]
I get the same error on OSX

**Comment by calumapplepie** [comment]
Same on linux

**Comment by LeopoldTal** [comment]
A very similar error on OSX (Sonoma) + Calibre 7.6.0: it complains about `ACSMInput_Prefs` instead. This happens with the latest release and with the current master.

```
calibre, version 7.6.0
ERROR: Unhandled exception: <b>InvalidPlugin</b>:Initialization of plugin Traceback (most recent call last):
  File "calibre/customize/ui.py", line 710, in initialize_plugin
  File "calibre_plugins.deacsm.__init__", line 316, in initialize
    deacsmprefs = prefs.ACSMInput_Prefs()
                  ^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'calibre_plugins.deacsm.prefs' has no attribute 'ACSMInput_Prefs'
 failed with traceback:
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 710, in initialize_plugin
  File "calibre_plugins.deacsm.__init__", line 316, in initialize
    deacsmprefs = prefs.ACSMInput_Prefs()
                  ^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'calibre_plugins.deacsm.prefs' has no attribute 'ACSMInput_Prefs'


calibre 7.6  embedded-python: True
macOS-14.2.1-arm64-arm-64bit Darwin ('64bit', '')
('Darwin', '23.2.0', 'Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:18 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6000')
Python 3.11.5
OSX: ('14.2.1', ('', '', ''), 'arm64')
Interface language: None
EXE path: /Applications/calibre.app/Contents/MacOS/calibre
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 9, 0) && DeDRM (10, 0, 9) && Package KFX (from KFX Input) (2, 9, 0) && KFX metadata reader (from KFX Input) (2, 9, 0) && From KFX (2, 9, 0) && KFX Input (2, 9, 0) && ACSM Input Plugin GUI Extension (0, 1, 0)
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 710, in initialize_plugin
  File "calibre_plugins.deacsm.__init__", line 316, in initialize
    deacsmprefs = prefs.ACSMInput_Prefs()
                  ^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'calibre_plugins.deacsm.prefs' has no attribute 'ACSMInput_Prefs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/gui2/preferences/plugins.py", line 325, in add_plugin
  File "calibre/customize/ui.py", line 520, in add_plugin
  File "calibre/customize/ui.py", line 715, in initialize_plugin
calibre.customize.InvalidPlugin: Initialization of plugin Traceback (most recent call last):
  File "calibre/customize/ui.py", line 710, in initialize_plugin
  File "calibre_plugins.deacsm.__init__", line 316, in initialize
    deacsmprefs = prefs.ACSMInput_Prefs()
                  ^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'calibre_plugins.deacsm.prefs' has no attribute 'ACSMInput_Prefs'
 failed with traceback:
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 710, in initialize_plugin
  File "calibre_plugins.deacsm.__init__", line 316, in initialize
    deacsmprefs = prefs.ACSMInput_Prefs()
                  ^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'calibre_plugins.deacsm.prefs' has no attribute 'ACSMInput_Prefs'
```

**Comment by Sebadier** [comment]
I had the same problem and it was related to the wrong openssl version installed by Homebrew on MacOS Sonoma
If you have homebrew installed you can unlink openssl of homebrew.

`brew unlink openssl@3`

Found the solution here: [https://www.mobileread.com/forums/showthread.php?t=341975&page=22](url)

**Comment by banool** [comment]
I get the same issue as above with MacOS:
```
calibre, version 7.12.0
ERROR: Unhandled exception: <b>InvalidPlugin</b>:Initialization of plugin Traceback (most recent call last):
  File "calibre/customize/ui.py", line 722, in initialize_plugin
  File "calibre_plugins.deacsm.__init__", line 294, in initialize
    deacsmprefs = prefs.ACSMInput_Prefs()
                  ^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'calibre_plugins.deacsm.prefs' has no attribute 'ACSMInput_Prefs'
 failed with traceback:
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 722, in initialize_plugin
  File "calibre_plugins.deacsm.__init__", line 294, in initialize
    deacsmprefs = prefs.ACSMInput_Prefs()
                  ^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'calibre_plugins.deacsm.prefs' has no attribute 'ACSMInput_Prefs'


calibre 7.12  embedded-python: True
macOS-14.5-arm64-arm-64bit Darwin ('64bit', '')
('Darwin', '23.5.0', 'Darwin Kernel Version 23.5.0: Wed May  1 20:12:58 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6000')
Python 3.11.5
OSX: ('14.5', ('', '', ''), 'arm64')
Interface language: None
EXE path: /Applications/calibre.app/Contents/MacOS/calibre
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 722, in initialize_plugin
  File "calibre_plugins.deacsm.__init__", line 294, in initialize
    deacsmprefs = prefs.ACSMInput_Prefs()
                  ^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'calibre_plugins.deacsm.prefs' has no attribute 'ACSMInput_Prefs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/gui2/preferences/plugins.py", line 322, in add_plugin
  File "calibre/customize/ui.py", line 532, in add_plugin
  File "calibre/customize/ui.py", line 727, in initialize_plugin
calibre.customize.InvalidPlugin: Initialization of plugin Traceback (most recent call last):
  File "calibre/customize/ui.py", line 722, in initialize_plugin
  File "calibre_plugins.deacsm.__init__", line 294, in initialize
    deacsmprefs = prefs.ACSMInput_Prefs()
                  ^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'calibre_plugins.deacsm.prefs' has no attribute 'ACSMInput_Prefs'
 failed with traceback:
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 722, in initialize_plugin
  File "calibre_plugins.deacsm.__init__", line 294, in initialize
    deacsmprefs = prefs.ACSMInput_Prefs()
                  ^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'calibre_plugins.deacsm.prefs' has no attribute 'ACSMInput_Prefs'
```

This is from trying to install DeACSM_0.0.16.zip.

Unlinking openssl 3.x.x and installing 1.x.x didn't help.

**Comment by tokiWren** [comment]
also experiencing this issue on debian linux. 
```
calibre, version 6.13.0
ERROR: Install plugin failed: A problem occurred while installing this plugin. This plugin will now be uninstalled. Please post the error message in details below into the forum thread for this plugin and restart calibre.

Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/customize/ui.py", line 677, in initialize_plugin
    p.initialize()
  File "calibre_plugins.deacsm.__init__", line 232, in initialize
    deacsmprefs = prefs.DeACSM_Prefs()
                  ^^^^^^^^^^^^^^^^^^
AttributeError: module 'calibre_plugins.deacsm.prefs' has no attribute 'DeACSM_Prefs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/gui2/dialogs/plugin_updater.py", line 710, in _install_clicked
    plugin = add_plugin(zip_path)
             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/calibre/calibre/customize/ui.py", line 487, in add_plugin
    plugin = initialize_plugin(plugin, path_to_zip_file, PluginInstallationType.EXTERNAL)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/calibre/calibre/customize/ui.py", line 682, in initialize_plugin
    raise InvalidPlugin((_('Initialization of plugin %s failed with traceback:')
calibre.customize.InvalidPlugin: Initialization of plugin Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/customize/ui.py", line 677, in initialize_plugin
    p.initialize()
  File "calibre_plugins.deacsm.__init__", line 232, in initialize
    deacsmprefs = prefs.DeACSM_Prefs()
                  ^^^^^^^^^^^^^^^^^^
AttributeError: module 'calibre_plugins.deacsm.prefs' has no attribute 'DeACSM_Prefs'
 failed with traceback:
Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/customize/ui.py", line 677, in initialize_plugin
    p.initialize()
  File "calibre_plugins.deacsm.__init__", line 232, in initialize
    deacsmprefs = prefs.DeACSM_Prefs()
                  ^^^^^^^^^^^^^^^^^^
AttributeError: module 'calibre_plugins.deacsm.prefs' has no attribute 'DeACSM_Prefs'
```

Tried it with the beta version linked in some other threads and got the same error.

**Comment by msegar** [comment]
> `brew unlink openssl@3`

Had same error and this worked for me.

**Operating system**

Mac

**Which version of Calibre are you running?**

7.22

**Which version of the ACSM Input plugin are you running?**

0.0.16

**Comment by Tauheed-Elahee** [comment]
I also get the same error on Debian Linux. Would like to know how to resolve the error.

> also experiencing this issue on debian linux.
> 
> ```
> calibre, version 6.13.0
> ERROR: Install plugin failed: A problem occurred while installing this plugin. This plugin will now be uninstalled. Please post the error message in details below into the forum thread for this plugin and restart calibre.
> 
> Traceback (most recent call last):
>   File "/usr/lib/calibre/calibre/customize/ui.py", line 677, in initialize_plugin
>     p.initialize()
>   File "calibre_plugins.deacsm.__init__", line 232, in initialize
>     deacsmprefs = prefs.DeACSM_Prefs()
>                   ^^^^^^^^^^^^^^^^^^
> AttributeError: module 'calibre_plugins.deacsm.prefs' has no attribute 'DeACSM_Prefs'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/lib/calibre/calibre/gui2/dialogs/plugin_updater.py", line 710, in _install_clicked
>     plugin = add_plugin(zip_path)
>              ^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/calibre/calibre/customize/ui.py", line 487, in add_plugin
>     plugin = initialize_plugin(plugin, path_to_zip_file, PluginInstallationType.EXTERNAL)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/calibre/calibre/customize/ui.py", line 682, in initialize_plugin
>     raise InvalidPlugin((_('Initialization of plugin %s failed with traceback:')
> calibre.customize.InvalidPlugin: Initialization of plugin Traceback (most recent call last):
>   File "/usr/lib/calibre/calibre/customize/ui.py", line 677, in initialize_plugin
>     p.initialize()
>   File "calibre_plugins.deacsm.__init__", line 232, in initialize
>     deacsmprefs = prefs.DeACSM_Prefs()
>                   ^^^^^^^^^^^^^^^^^^
> AttributeError: module 'calibre_plugins.deacsm.prefs' has no attribute 'DeACSM_Prefs'
>  failed with traceback:
> Traceback (most recent call last):
>   File "/usr/lib/calibre/calibre/customize/ui.py", line 677, in initialize_plugin
>     p.initialize()
>   File "calibre_plugins.deacsm.__init__", line 232, in initialize
>     deacsmprefs = prefs.DeACSM_Prefs()
>                   ^^^^^^^^^^^^^^^^^^
> AttributeError: module 'calibre_plugins.deacsm.prefs' has no attribute 'DeACSM_Prefs'
> ```
> 
> Tried it with the beta version linked in some other threads and got the same error. edit: After a reboot, I'm getting a different "error detecting version of libcrypto". I guess they're related.

**Comment by speetzer** [comment]
I have the same error Linux. Any fix found?

**Comment by calumapplepie** [comment]
@speetzer Does the released .zip work? I somehow solved the issue, but I forget how.  The .zip Calibre has in it's `.config/` folder is identical to that of the released plugin, however.

**Comment by calumapplepie** [comment]
I may have had to install libcrypto++ ?  Other possibilities include something to do with python in the wine host for adobe digital editions, but that might be a later step.  Sadly, while I have my syslog from when I fixed it, my bash_history from that session does not appear to have saved; so I can only see commands involving root.  I may have also created ~/.config/calibre/plugins/deacsm.json manually.

**Comment by CrawlerBleak** [comment]
With or without openssl@3 linked, I also encounter this issue with DeACSM 0.0.16, Calibre 9.7, and macOS Sequoia 15.7.4.
