### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by bspacausa** [Leseratte10/acsm-calibre-plugin#97]
### Bug description

I have been successfully using DeACSM on my Windows machine for a few years(thank you!!) but today it stopped converting to epub. I have tried to uninstall and re-install (including deleting C:\Users\Admin\AppData\Roaming\calibre) with the same error. Please see below. Any suggestions on how to fix?

Looking at a similar past issue #6, I did try to visit https://ofs.contentreserve.com/ACSNotificationService.svc/Notify and did see the "Method not allowed" error. Side note, I started a fresh install of calibre/deacsm/dedrm on my Mac and have no issues using the same AdobeID, therefore likely it is not an account or network issue.

ApplicationPaletteChange event ignored
Using calibre Qt style: True
calibre Debug log
calibre 7.12  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.11.5
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: DeACSM (0, 0, 16) && DeDRM (10, 0, 9)
calibre 7.12  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.11.5
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: DeACSM (0, 0, 16) && DeDRM (10, 0, 9)
QPA platform: windows
devicePixelRatio: 1.25
logicalDpi: 96.0 x 96.0
physicalDpi: 113.41395348837209 x 113.12164948453608
[0.00] Starting up...
[0.02] Showing splash screen...
[0.17] splash screen shown
[0.17] Initializing db...
[0.19] db initialized
[0.19] Constructing main UI...
[0.73] GUI main window shown
[0.81] main UI initialized...
[0.81] Hiding splash screen
[26.58] splash screen hidden
[26.58] Started up in 26.58 seconds with 127 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\x99g\x85B\\`\t\xb894\x8cW\xd5\xdf\xef|6z\xc5\x9f\xff\xe0\x82\x9fk\xa7l%\xf68?\xe0', b'C:\\Users\\Admin\\Downloads\\BookName_9780307907035_601668.acsm']
Running file type plugin DeACSM failed with traceback:
Traceback (most recent call last):
  File "urllib\request.py", line 1348, in do_open
  File "http\client.py", line 1286, in request
  File "http\client.py", line 1332, in _send_request
  File "http\client.py", line 1281, in endheaders
  File "http\client.py", line 1041, in _send_output
  File "http\client.py", line 979, in send
  File "http\client.py", line 1458, in connect
  File "ssl.py", line 517, in wrap_socket
  File "ssl.py", line 1108, in _create
  File "ssl.py", line 1379, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 199, in _run_filetype_plugins
  File "calibre_plugins.deacsm.__init__", line 422, in run
  File "calibre_plugins.deacsm.__init__", line 324, in download
  File "C:\Users\Admin\AppData\Roaming\calibre\plugins\DeACSM.zip\libadobe.py", line 267, in sendHTTPRequest_DL2FILE
  File "urllib\request.py", line 216, in urlopen
  File "urllib\request.py", line 519, in open
  File "urllib\request.py", line 536, in _open
  File "urllib\request.py", line 496, in _call_chain
  File "urllib\request.py", line 1391, in https_open
  File "urllib\request.py", line 1351, in do_open
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)>
DeACSM v0.0.16: Trying to parse file BookName_9780307907035_601668.acsm
DeACSM v0.0.16: Try to fulfill ...
Notifying server ...
Notifying server https://acsepub.contentreserve.com/fulfillment/FulfillmentNotification
Fulfillment notification successful.
Notifying optional server https://ofs.contentreserve.com/ACSNotificationService.svc/Notify
Weird Fulfillment Notification response: 
DeACSM v0.0.16: Downloading book ...
DeACSM v0.0.16: Loading book from https://acs.cdn.overdrive.com/ACSStore1/0111-1/93A/5D3/EB/{93A5D3EB-2DF4-4F12-BB68-5BD7983B898A}Fmt410.epub

### Operating system

Windows

### Which version of Calibre are you running?

7.12

### Which version of the ACSM Input plugin are you running?

v0.0.16

### Import type

Clicking the 'Add books' button in the menu bar

**Comment by hot-soup** [comment]
I'm experiencing the same issue as well. Tried importing a book today and Calibre does not download the epub version of the book and just imports the .ascm file.

ApplicationPaletteChange event ignored
Using calibre Qt style: True
calibre Debug log
calibre 6.27  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.10.1
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeACSM (0, 0, 16) && DeDRM (10, 0, 3)
calibre 6.27  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.10.1
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeACSM (0, 0, 16) && DeDRM (10, 0, 3)
QPA platform: windows
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 95.97550058892816 x 96.07176470588234
[0.00] Starting up...
[0.00] Showing splash screen...
[0.19] splash screen shown
[0.19] Initializing db...
[0.22] db initialized
[0.22] Constructing main UI...
[0.91] main UI initialized...
[0.91] Hiding splash screen
Starting QuickView
[12.94] splash screen hidden
[12.94] Started up in 12.94 seconds with 775 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'-\xb3_\x9b\n$2H\xc4\t\xc6h\xf7\x96\xbb\x8c\xff\xdf\x84M\xe0\x0e\xf2\x85\x9f\xc3\x8d\x0fa\\\xd9\xcd', b'E:\\dl\\LegendsLattes_9781250886095_9041166.acsm']
Running file type plugin DeACSM failed with traceback:
Traceback (most recent call last):
  File "urllib\request.py", line 1348, in do_open
  File "http\client.py", line 1282, in request
  File "http\client.py", line 1328, in _send_request
  File "http\client.py", line 1277, in endheaders
  File "http\client.py", line 1037, in _send_output
  File "http\client.py", line 975, in send
  File "http\client.py", line 1454, in connect
  File "ssl.py", line 512, in wrap_socket
  File "ssl.py", line 1070, in _create
  File "ssl.py", line 1341, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 187, in _run_filetype_plugins
  File "calibre_plugins.deacsm.__init__", line 422, in run
  File "calibre_plugins.deacsm.__init__", line 324, in download
  File "C:\Users\hotsoup\AppData\Roaming\calibre\plugins\DeACSM.zip\libadobe.py", line 267, in sendHTTPRequest_DL2FILE
  File "urllib\request.py", line 216, in urlopen
  File "urllib\request.py", line 519, in open
  File "urllib\request.py", line 536, in _open
  File "urllib\request.py", line 496, in _call_chain
  File "urllib\request.py", line 1391, in https_open
  File "urllib\request.py", line 1351, in do_open
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>
DeACSM v0.0.16: Trying to parse file LegendsLattes_9781250886095_9041166.acsm
DeACSM v0.0.16: Try to fulfill ...
Notifying server ...
Notifying server https://acsepub.contentreserve.com/fulfillment/FulfillmentNotification
Fulfillment notification successful.
Notifying optional server https://ofs.contentreserve.com/ACSNotificationService.svc/Notify
Weird Fulfillment Notification response: 
DeACSM v0.0.16: Downloading book ...
DeACSM v0.0.16: Loading book from https://acs.cdn.overdrive.com/ACSStore1/2390-1/85D/EE2/63/{85DEE263-7972-4B3F-834B-C255D17EAB6D}Fmt410.epub

Operating system
Windows 11

Which version of Calibre are you running?
6.27

Which version of the ACSM Input plugin are you running?
v0.0.16

Import type
Clicking the 'Add books' button in the menu bar

Further information
No response

**Comment by Leseratte10** [comment]
Sorry, looks like I missed this bug report. 

In general, this SSL error always refers to the last URL displayed in the log; in this case it would be the URL to the encrypted EPUB file that it's failing to download. 

Can you check if you can download that through your browser? When I do that right now I successfully get the file, so either it's an issue specific to your computer(s), or the library has already fixed the issue within the last month. 

Given that similar issues seem to show up from time to time, I'll try to add a settings parameter to allow completely disabling any SSL validation when I have some more time.

**Comment by Leseratte10** [comment]
Please give the latest beta build a try, the issue should be fixed.

**Comment by GaudiestTooth17** [comment]
I just had this issue, so it looks like it's been reintroduced:

```
DeACSM v0.0.16: Exporting encryption key to /home/alex/Documents/epubs/calibre-plugins/adobe_uuid_5d12d46d-5e34-47be-8d13-39094602c241.der
DeACSM v0.0.16: Trying to parse file JournalofDiscoursesV_9781629736334_3399742.acsm
DeACSM v0.0.16: Try to fulfill ...
DeACSM v0.0.16: Hey, that didn't work: 
Looks like there's been an error during Fulfillment: <error xmlns="http://ns.adobe.com/adept" data="E_ADEPT_REQUEST_EXPIRED http://acsepub.contentreserve.com/fulfillment/Fulfill 2026-05-07T05:12:46-04:00%20(1778145166000)%20is%20before%202026-05-09T16:04:39-04:00%20(1778357079402)"/>

qt.qpa.wayland.textinput: virtual void QtWaylandClient::QWaylandTextInputv3::disableSurface(wl_surface*) Try to disable surface 0x55b64fc69eb0 with focusing surface 0x55b65027f340
qt.qpa.wayland.textinput: virtual void QtWaylandClient::QWaylandTextInputv3::disableSurface(wl_surface*) Try to disable surface 0x55b64fc69eb0 with focusing surface 0x55b650280360
DeACSM v0.0.16: Trying to parse file JournalofDiscoursesV_9781629736334_3399742.acsm
DeACSM v0.0.16: Try to fulfill ...
Notifying server ...
Notifying server https://acsepub.contentreserve.com/fulfillment/FulfillmentNotification
Fulfillment notification successful.
Notifying optional server https://ofs.contentreserve.com/ACSNotificationService.svc/Notify
Weird Fulfillment Notification response: 
DeACSM v0.0.16: Downloading book ...
DeACSM v0.0.16: Loading book from https://acs.cdn.overdrive.com/ACSStore1/4970-1/51C/6C2/E7/{51C6C2E7-4557-407B-BF49-AE54E55E63DC}Fmt410.epub
Running file type plugin DeACSM failed with traceback:
Traceback (most recent call last):
  File "urllib/request.py", line 1321, in do_open
  File "http/client.py", line 1358, in request
  File "http/client.py", line 1404, in _send_request
  File "http/client.py", line 1353, in endheaders
  File "http/client.py", line 1113, in _send_output
  File "http/client.py", line 1057, in send
  File "http/client.py", line 1499, in connect
  File "ssl.py", line 455, in wrap_socket
  File "ssl.py", line 1076, in _create
  File "ssl.py", line 1372, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1081)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 236, in _run_filetype_plugins
  File "calibre_plugins.deacsm.__init__", line 422, in run
    rpl = self.download(replyData)
  File "calibre_plugins.deacsm.__init__", line 324, in download
    ret = sendHTTPRequest_DL2FILE(download_url, filename_tmp)
  File "/home/alex/.config/calibre/plugins/DeACSM.zip/libadobe.py", line 267, in sendHTTPRequest_DL2FILE
    handler = ulib.urlopen(req)
  File "urllib/request.py", line 187, in urlopen
  File "urllib/request.py", line 487, in open
  File "urllib/request.py", line 504, in _open
  File "urllib/request.py", line 464, in _call_chain
  File "urllib/request.py", line 1369, in https_open
  File "urllib/request.py", line 1324, in do_open
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1081)>
DeACSM v0.0.16: Trying to parse file JournalofDiscoursesV_9781629736334_3399742.acsm
DeACSM v0.0.16: Try to fulfill ...
Notifying server ...
Notifying server https://acsepub.contentreserve.com/fulfillment/FulfillmentNotification
Fulfillment notification successful.
Notifying optional server https://ofs.contentreserve.com/ACSNotificationService.svc/Notify
Weird Fulfillment Notification response: 
DeACSM v0.0.16: Downloading book ...
DeACSM v0.0.16: Loading book from https://acs.cdn.overdrive.com/ACSStore1/4970-1/51C/6C2/E7/{51C6C2E7-4557-407B-BF49-AE54E55E63DC}Fmt410.epub
Running file type plugin DeACSM failed with traceback:
Traceback (most recent call last):
  File "urllib/request.py", line 1321, in do_open
  File "http/client.py", line 1358, in request
  File "http/client.py", line 1404, in _send_request
  File "http/client.py", line 1353, in endheaders
  File "http/client.py", line 1113, in _send_output
  File "http/client.py", line 1057, in send
  File "http/client.py", line 1499, in connect
  File "ssl.py", line 455, in wrap_socket
  File "ssl.py", line 1076, in _create
  File "ssl.py", line 1372, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1081)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 236, in _run_filetype_plugins
  File "calibre_plugins.deacsm.__init__", line 422, in run
    rpl = self.download(replyData)
  File "calibre_plugins.deacsm.__init__", line 324, in download
    ret = sendHTTPRequest_DL2FILE(download_url, filename_tmp)
  File "/home/alex/.config/calibre/plugins/DeACSM.zip/libadobe.py", line 267, in sendHTTPRequest_DL2FILE
    handler = ulib.urlopen(req)
  File "urllib/request.py", line 187, in urlopen
  File "urllib/request.py", line 487, in open
  File "urllib/request.py", line 504, in _open
  File "urllib/request.py", line 464, in _call_chain
  File "urllib/request.py", line 1369, in https_open
  File "urllib/request.py", line 1324, in do_open
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1081)>
DeDRM v10.0.3: Trying to decrypt {51C6C2E7-4557-407B-BF49-AE54E55E63DC}Fmt410.epub
DeDRM v10.0.3: Verifying zip archive integrity
FontDecrypt: Checking OEBPS/content.opf for IETF font obfuscation keys ... found 'urn:uuid:f796852c-5470-4d22-9c24-7f7532a8d61a' (BookId)
FontDecrypt: Checking OEBPS/content.opf for Adobe font obfuscation keys ... found 'f796852c54704d229c247f7532a8d61a'
FontDecrypt: There's remaining entries in encryption.xml, adding file ...
DeDRM v10.0.3: Post-processing took 0.6 seconds
DeDRM v10.0.3: Finished after 0.8 seconds
Failed to count pages in book: 7 EPUB because it is DRM locked
qt.qpa.wayland.textinput: virtual void QtWaylandClient::QWaylandTextInputv3::enableSurface(wl_surface*) Try to enable surface 0x55b64ec8d210 with focusing surface 0x55b6505e6460
qt.qpa.wayland.textinput: virtual void QtWaylandClient::QWaylandTextInputv3::disableSurface(wl_surface*) Try to disable surface 0x55b6505e6460 with focusing surface 0x55b64ec8d210
gio: https://manual.calibre-ebook.com/drm.html: Failed to execute child process “gio-launch-desktop” (No such file or directory)
gio: https://manual.calibre-ebook.com/drm.html: Failed to execute child process “gio-launch-desktop” (No such file or directory)
```

The work around was the same as before, open the second URL in a web browser.

**Comment by linnealovespie** [comment]
@GaudiestTooth17 I also started seeing this error again. How does one run the downloaded file through De-DRM afterwards? I'm having issues with that step even with the workaround.

**Comment by GaudiestTooth17** [comment]
Unfortunately, I got stuck at the same point with running it through DeDRM and I just gave up ☹️ . You can look at that discussion here: https://github.com/noDRM/DeDRM_tools/issues/1009

If that looks like the same issue you are experiencing, you could try posting and reopening.

**Comment by ritlew** [comment]
I was able to get deASCM to work after following the steps in the ["Building from Source" section](https://github.com/Leseratte10/acsm-calibre-plugin#building-from-source)
